In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
# Raw data file
 
# read the dataset using the compression zip
df = pd.read_csv('../Okcupid.csv')
 
# display dataset
df.head()

,Unnamed: 0,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,1,35,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,2,38,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,3,23,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,4,29,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [3]:
df1=df.drop(['Unnamed: 0'], axis = 1)

In [4]:
df1.head()

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,hospitality / travel,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1,NaN,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000,student,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [5]:
df1['smokes'].value_counts()

no                43896
sometimes          3787
when drinking      3040
yes                2231
trying to quit     1480
Name: smokes, dtype: int64

In [6]:
df1['speaks'].value_counts()

english                                                                21828
english (fluently)                                                      6628
english (fluently), spanish (poorly)                                    2059
english (fluently), spanish (okay)                                      1917
english (fluently), spanish (fluently)                                  1288
                                                                       ...
english (fluently), urdu (poorly), japanese (poorly), french (okay)        1
english, spanish, hindi, c++                                               1
english (fluently), japanese (okay), thai (okay), chinese (poorly)         1
english (fluently), french (okay), italian (okay), hebrew (okay)           1
english (fluently), french, farsi                                          1
Name: speaks, Length: 7647, dtype: int64

In [7]:
#languages=df1['speaks'].value_counts()
languages=df['speaks'].value_counts().head(60)
languages

english                                                     21828
english (fluently)                                           6628
english (fluently), spanish (poorly)                         2059
english (fluently), spanish (okay)                           1917
english (fluently), spanish (fluently)                       1288
english, spanish                                              859
english (fluently), french (poorly)                           756
english, spanish (okay)                                       655
english, spanish (poorly)                                     609
english (fluently), chinese (fluently)                        535
english (fluently), french (okay)                             532
english (fluently), chinese (okay)                            430
english (poorly)                                              310
english, chinese                                              306
english (okay)                                                306
english (fluently), german (poorly)                           263
english, french (poorly)                                      245
english (fluently), french (fluently)                         215
english, french (okay)                                        210
english, french                                               209
english, spanish (fluently)                                   198
english (fluently), japanese (poorly)                         184
english (fluently), chinese (poorly)                          175
english (fluently), german (okay)                             160
english (fluently), russian (fluently)                        147
english (fluently), spanish (okay), french (poorly)           143
english (fluently), spanish (fluently), french (poorly)       143
english (fluently), french (okay), spanish (poorly)           133
english (fluently), french (poorly), spanish (poorly)         130
english (fluently), italian (poorly)                          115
english (fluently), japanese (okay)                           113
english (fluently), hindi (fluently)                          101
english, russian                                              101
english (fluently), italian (okay)                             98
english (fluently), sign language (okay)                       97
english (fluently), german (fluently)                          93
english (fluently), spanish (poorly), french (poorly)          93
english (fluently), tagalog (fluently)                         87
english, chinese (okay)                                        86
english, english                                               84
english, german (poorly)                                       82
english (fluently), sign language (poorly)                     78
english (fluently), french (fluently), spanish (okay)          76
english (fluently), c++ (okay)                                 72
english (fluently), c++ (fluently)                             70
english (fluently), chinese (okay), spanish (poorly)           69
english (fluently), spanish (fluently), french (okay)          69
english, chinese (poorly)                                      67
english (fluently), japanese (fluently)                        66
english (okay), spanish (poorly)                               64
english (fluently), tagalog (okay)                             64
english, hindi                                                 63
english (okay), spanish (fluently)                             62
english, german                                                61
english (fluently), korean (okay)                              60
english (fluently), french (fluently), spanish (poorly)        58
english (fluently), spanish (fluently), italian (poorly)       57
english, japanese                                              57
english (fluently), c++ (poorly)                               56
english (fluently), spanish (okay), italian (poorly)           56
Name: speaks, dtype: int64

In [8]:
df1['status'].value_counts()

single            55697
seeing someone     2064
available          1865
married             310
unknown              10
Name: status, dtype: int64

In [19]:
spec_chars = ["(",")", "fluently", "poorly", "okay"]
for char in spec_chars:
    df['speaks'] = df['speaks'].str.replace(char, ' ')
    
df['speaks']

/var/folders/ng/g2rw737s09b_hmsyrmqzpq300000gn/T/ipykernel_66425/1130529553.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['speaks'] = df['speaks'].str.replace(char, ' ')

0                                                  english
1                     english    , spanish    , french
2                                     english, french, c++
3                                      english, german
4                                                  english
                               ...
59941                                              english
59942                                          english
59943                                          english
59944    english    , spanish    , chinese    , korean ...
59945                                              english
Name: speaks, Length: 59946, dtype: object

In [10]:
#languages = df1.speaks.str.split(",")
#languages
#languages_cleaned=languages.str.get(1)
#languages_cleaned
#sns.countplot(data=df1, x="languages");

In [11]:
english=pd.DataFrame(df1[(df1.speaks == 'english') | (df1.speaks == 'english (fluently)')])
english.head()

#movies[(movies.duration >= 200) & (movies.genre == 'Drama')]

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
4,29,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
6,32,fit,strictly anything,socially,never,graduated from college/university,"white, other",65.0,-1,NaN,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,f,virgo,NaN,english,single
8,24,NaN,strictly anything,socially,NaN,graduated from college/university,white,67.0,-1,NaN,...,"belvedere tiburon, california",doesn&rsquo;t have kids,straight,likes dogs and likes cats,christianity but not too serious about it,f,gemini but it doesn&rsquo;t matter,when drinking,english,single
9,37,athletic,mostly anything,not at all,never,working on two-year college,white,65.0,-1,student,...,"san mateo, california",NaN,straight,likes dogs and likes cats,atheism and laughing about it,m,cancer but it doesn&rsquo;t matter,no,english (fluently),single

In [12]:
#filter_list = ['spanish (fluently)', 'spanish (poorly)', 'spanish (okay)']
df1[['1', '2', '3']]=df1.speaks.str.split(",", n=2, expand=True)

In [13]:
df1

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,pets,religion,sex,sign,smokes,speaks,status,1,2,3
0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,...,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single,english,None,None
1,35,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,hospitality / travel,...,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single,english (fluently),spanish (poorly),french (poorly)
2,38,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1,NaN,...,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available,english,french,c++
3,23,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000,student,...,likes cats,NaN,m,pisces,no,"english, german (poorly)",single,english,german (poorly),None
4,29,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,...,likes dogs and likes cats,NaN,m,aquarius,no,english,single,english,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,NaN,NaN,socially,never,graduated from college/university,NaN,62.0,-1,sales / marketing / biz dev,...,has dogs,catholicism but not too serious about it,f,cancer and it&rsquo;s fun to think about,no,english,single,english,None,None
59942,24,fit,mostly anything,often,sometimes,working on college/university,"white, other",72.0,-1,entertainment / media,...,likes dogs and likes cats,agnosticism,m,leo but it doesn&rsquo;t matter,no,english (fluently),single,english (fluently),None,None
59943,42,average,mostly anything,not at all,never,graduated from masters program,asian,71.0,100000,construction / craftsmanship,...,NaN,christianity but not too serious about it,m,sagittarius but it doesn&rsquo;t matter,no,english (fluently),single,english (fluently),None,None
59944,27,athletic,mostly anything,socially,often,working on college/university,"asian, black",73.0,-1,medicine / health,...,likes dogs and likes cats,agnosticism but not too serious about it,m,leo and it&rsquo;s fun to think about,trying to quit,"english (fluently), spanish (poorly), chinese ...",single,english (fluently),spanish (poorly),"chinese (poorly), korean (poorly), japanese (..."
59945,39,average,NaN,socially,NaN,graduated from masters program,white,68.0,-1,medicine / health,...,likes dogs and likes cats,catholicism and laughing about it,m,gemini and it&rsquo;s fun to think about,sometimes,english,single,english,None,None

In [14]:
language_df = df1.astype(object).replace(np.nan, 'None')


language_df

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,pets,religion,sex,sign,smokes,speaks,status,1,2,3
0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,...,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single,english,None,None
1,35,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,hospitality / travel,...,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single,english (fluently),spanish (poorly),french (poorly)
2,38,thin,anything,socially,None,graduated from masters program,None,68.0,-1,None,...,has cats,None,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available,english,french,c++
3,23,thin,vegetarian,socially,None,working on college/university,white,71.0,20000,student,...,likes cats,None,m,pisces,no,"english, german (poorly)",single,english,german (poorly),None
4,29,athletic,None,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,...,likes dogs and likes cats,None,m,aquarius,no,english,single,english,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,None,None,socially,never,graduated from college/university,None,62.0,-1,sales / marketing / biz dev,...,has dogs,catholicism but not too serious about it,f,cancer and it&rsquo;s fun to think about,no,english,single,english,None,None
59942,24,fit,mostly anything,often,sometimes,working on college/university,"white, other",72.0,-1,entertainment / media,...,likes dogs and likes cats,agnosticism,m,leo but it doesn&rsquo;t matter,no,english (fluently),single,english (fluently),None,None
59943,42,average,mostly anything,not at all,never,graduated from masters program,asian,71.0,100000,construction / craftsmanship,...,None,christianity but not too serious about it,m,sagittarius but it doesn&rsquo;t matter,no,english (fluently),single,english (fluently),None,None
59944,27,athletic,mostly anything,socially,often,working on college/university,"asian, black",73.0,-1,medicine / health,...,likes dogs and likes cats,agnosticism but not too serious about it,m,leo and it&rsquo;s fun to think about,trying to quit,"english (fluently), spanish (poorly), chinese ...",single,english (fluently),spanish (poorly),"chinese (poorly), korean (poorly), japanese (..."
59945,39,average,None,socially,None,graduated from masters program,white,68.0,-1,medicine / health,...,likes dogs and likes cats,catholicism and laughing about it,m,gemini and it&rsquo;s fun to think about,sometimes,english,single,english,None,None